# Change these first
owner: 1Ronkkeli # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Game-Panel | Central Management For Gamehosting |
    url: https://panel.ronkkeli.net
  - name: Game-Panel | BETA | | Non Public |
    url: odyssey.panel.gg
    port: 80
    check: "tcp-ping"
  - name: ronkkeli.com | Main Website | Customer/Billing portal |
    url: https://www.ronkkeli.com
  - name: Web-1 | SPANEL | Main Webhosting |
    url: https://cloud-4b162c.managed-vps.net/hostpanel/login
  - name: Game1 | Minecraft + Other games |
    url: game1.ronkkeli.net
    port: 8080
    check: "tcp-ping"
  - name: Game2 | FiveM |
    url: game2.ronkkeli.net
    port: 8080
    check: "tcp-ping"
  - name: Game3 | FiveM |
    url: game3.ronkkeli.net
    port: 8080
    check: "tcp-ping"
  - name: Game4 | Beta non public |
    url: 135.181.58.27
    port: 8080
    check: "tcp-ping"
  - name: Database Cloud Infrastructure | panel.ronkkeli.net |
    url: phpmyadmin-gra3.hosting.ovh.net
    port: 80
    check: "tcp-ping"
  - name: ronkkeli.net | Mail | Non Critical | Ticket Team Mails |
    url: https://webmail.ronkkeli.net
  - name: ronkkeli.com | Mail | Billing/Panel + Other notifications | Main Company Emails |
    url: mail.google.com
    port: 80
    check: "tcp-ping"
  - name: docs.ronkkeli.net | Documentation Platform |
    url: https://docs.ronkkeli.net
  - name: Discord Tickets Bot
    url: 91.107.212.48
    port: 80
    check: "tcp-ping"
   
    


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ronkkeli.net
  # baseUrl: /your-repo-name
  logoUrl: https://ronkkeli.com/header-white.png
  name: www.ronkkeli.com
  introTitle: "Service Status"
  introMessage: Status for all of our Public / Non public Servers.
  navbar:
    - title: Status
      href: /
    - title: Our Website
      href: https://www.ronkkeli.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
