# Change these first
owner: 1Ronkkeli # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Game-Panel
    url: https://panel.ronkkeli.net
  - name: Game-Panel | BETA
    url: https://odyssey.panel.gg/
  - name: Customer Portal / Website
    url: https://www.ronkkeli.com
  - name: Web-1 | SPANEL
    url: https://cloud-4b162c.managed-vps.net/hostpanel/login


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ronkkeli.net
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Ronkkeli Hosting
  introTitle: "Ronkkeli Hosting"
  introMessage: Status Page For Ronkkeli Hosting | www.ronkkeli.com
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
